---
server:
    install: '1'
    timezone: Asia/Tokyo
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: default, ip: 192.168.33.99, memory: '1024', sharedfolder: ./src, enableWindows: '1', useVagrantCloud: '1', syncType: nfs }
apache:
    install: '1'
    docroot: /vagrant
    servername: iweee.vb
mysql:
    install: '1'
    root_password: '123'
    database: db
    user: user
    password: password
    dump: ''
sqlite:
    install: '1'
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-gd, php5-sqlite, php5-mysql]
